### ISSUE TITLE
[app] pairdrop

### ISSUE THREAD

**Issue by funkypenguin** [elfhosted/enhancements#11]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/eflhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

It's a simple PWA which (when served with a proper TLS cert) lets you do "local airdrop"

### 🏠 Project Homepage

https://github.com/RobinLinus/snapdrop

**Comment by davidemarcoli** [comment]
There is a snapdrop fork called Pairdrop which has extra features such as:
* Device Pairing (to enable connections on public Wi-Fi, company/university networks, Apple Private Relay, VPN etc.) --> Only uses the server for the initial connection
* Improved UI
* Integration into device share / context menus

https://github.com/schlagmichdoch/PairDrop
https://pairdrop.net/

**Comment by funkypenguin** [comment]
Pairdrop is in the store, very useful addition! :)
