### ISSUE TITLE
[app] Threadfin

### ISSUE THREAD

**Issue by jrcorwin** [elfhosted/enhancements#13]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/eflhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

![threadfin](https://github.com/user-attachments/assets/73b80ab7-ebde-43ee-98bd-1480d9c398b7)

**Threadfin:**
_"M3U Proxy for Plex DVR and Emby/Jellyfin Live TV. Based on xTeVe."_

Directly from their GitHub:

**Threadfin Features**
- New Bootstrap based UI
- RAM based buffer instead of File based

Filter Group
- Can now add a starting channel number for the filter group

Map Editor
- Can now multi select Bulk Edit by holding shift
- Now has a separate table for inactive channels
- Can add 3 backup channels for an active channel (backup channels do NOT have to be active)
- Alpha Numeric sorting now sorts correctly
- Can now add a starting channel number for Bulk Edit to renumber multiple channels at a time
- PPV channels can now map the channel name to an EPG
- Removed old Threadfin buffer option, since FFMPEG/VLC will always be a better solution

**xTeVe Features**
Files
- Merge external M3U files
- Merge external XMLTV files
- Automatic M3U and XMLTV update
- M3U and XMLTV export
Channel management
- Filtering streams
- Channel mapping
- Channel order
- Channel logos
- Channel categories
Streaming
- Buffer with HLS / M3U8 support
- Re-streaming
- Number of tuners adjustable
- Compatible with Plex / Emby / Jellyfin EPG

### 🏠 Project Homepage

https://github.com/Threadfin/Threadfin

### 💬 Your Discord username

bsm5702

**Comment by funkypenguin** [comment]
ThreadFin is in the store, ready for early-adopters to test
