### ISSUE TITLE
[app] Plex-Trakt-Sync

### ISSUE THREAD

**Issue by jrcorwin** [elfhosted/enhancements#15]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/eflhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

_"This project adds a two-way-sync between trakt.tv and Plex Media Server. It requires a trakt.tv account but no Plex premium and no Trakt VIP subscriptions, unlike the Plex app provided by Trakt."_

### 🏠 Project Homepage

https://github.com/Taxel/PlexTraktSync

### 💬 Your Discord username

bsm5702

**Comment by funkypenguin** [comment]
Added to ElfTerm, and rolled out! 👍🏻
