### ISSUE TITLE
[suggestion] Automatically disabling plex_update.sh for non-Plex-Debrid tenants

### ISSUE THREAD

**Issue by jrcorwin** [elfhosted/enhancements#19]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app

### 🤕 What's not right?

Plex-Debrid subscribers rely upon Zurg using `plex_update.sh`, in order to update their Plex libraries. However, if they transition away from Plex-Debrid and begin using Riven this can cause issues. Riven needs to handle triggering Plex library updates entirely on its own. Similarly, Autoscan needs to handle triggering Plex library updates for Radarr/Sonarr.

If `plex_update.sh` is left active it will trigger Plex library updates when new content is added to Zurg and then Riven or Autoscan will also be attempting their own Plex library updates based upon content being added to the symlink folders. Not only does this lead to Plex being hammered by additional and unnecessary triggers, but it can conflict with Riven or Autoscan's ability function properly.

### 🤯 Here's my idea!

Would it be possible, through some automated/scripted process, to only enable `plex_update.sh` for Plex-Debrid bundles and to disable `plex_update.sh` for Riven or Radarr/Sonarr bundles? 

### 🤔 On the other hand..

While it would provide tenants with a smoother onboarding process and avoid issues, Is this more work than it is worth? Would it be better to simply inform tenants within the guides associated with their bundles and place the responsibility for doing this on them? 

Could this be enabled/disabled with an ElfBot command, if not done through an automated/scripted process for tenants. 

### 🤩 But will it fly?

That I don't know. It seems that we can possibly do something like, but I don't have the know-how for it. 

### 💬 Your Discord username

bsm5702

**Comment by funkypenguin** [comment]
This has been done :)
