### ISSUE TITLE
Add Zurg stats to Homer dashboard

### ISSUE THREAD

**Issue by funkypenguin** [elfhosted/enhancements#2]
We used to display disk usage stats on our Homer dashboards, but these were disabled due to the I/O load they added, and now with the demise of ElfStorage, they're irrelevant anyway.

I thought it would be more useful to display the user's RD stats (as scraped from Zurg, which now has a .json endpoint), as described at https://github.com/bastienwirtz/homer/blob/main/docs/tips-and-tricks.md#get-the-news-headlines-in-homer

Our original disk calculations and JSON creation can be found here: https://github.com/elfhosted/myprecious/blob/d8f752025a4f4d5f70e38612c57b1851eabc9d37/charts/myprecious/templates/configmaps/configmap-homer-config.yaml#L29

While we **could** potentially scrape the Zurg API directly with homer, I thought it might make more sense to resurrect the old code, but to alter it to pull stats on an interval. This way, we could still display useful information for non-Zurg users, add more details like a temporary announcement, etc.

Changes should be testable running a local instance of Homer :)

**Comment by yowmamasita** [comment]
Plan of action here:

- `disk_usage.sh` to scrape zurg's `/stats` endpoint and save it to `zurg-stats.json`
- configure homer (config.yml) to get status from `zurg-stats.json`

**Comment by funkypenguin** [comment]
I did the first cut of this, here : https://github.com/elfhosted/myprecious/blob/2f6e611f36ca7bcb3fa3fa629eaf5124ca31586c/charts/myprecious/templates/configmaps/configmap-homer-config.yaml#L91

**Comment by yowmamasita** [comment]
So just fetch it directly, no more file middleware?

**Comment by funkypenguin** [comment]
Yeah, because we only get one message section, and we might need to include other info (like Riven stats) :)

**Comment by jrcorwin** [comment]
A tenant (Achmed) requested the ability to see when their ElfHosted subs are set to expire directly from the Dashboard as well. Not sure how well that might work with only having that one message section however.

**Comment by funkypenguin** [comment]
@yowmamasita mentioned that this (reporting on token expiry) is coming to Zurg in time

**Comment by funkypenguin** [comment]
When more details are available from Zurg (download token expiry, etc), we can update this, but this EEP is done :)
