### ISSUE TITLE
[app] Petio

### ISSUE THREAD

**Issue by jrcorwin** [elfhosted/enhancements#24]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

Request, review and discover companion app for plex.

Allow your users to interact with media both on and off your server with this app. Available as a docker image and also as binaries. Features a React frontend utilizing Redux and a Node JS express API and MongoDb database.

_They have a `main` branch and a `dev` branch. Maybe we can test both..._

### 🏠 Project Homepage

https://github.com/petio-team/petio

### 💬 Your Discord username

bsm5702

**Comment by funkypenguin** [comment]
Done :) 

https://elfhosted.com/app/petio/
