### ISSUE TITLE
[app] Requestrr

### ISSUE THREAD

**Issue by layezee20** [elfhosted/enhancements#27]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

Requestrr is a chatbot used to simplify using services like Sonarr/Radarr/Overseerr/Ombi via the use of chat!

Features
Ability to request content via Discord using slash commands, buttons and more!
Users can get notified when their requests complete
Sonarr (V2-V4) & Radarr (V2-V5) integration with support for multiple instance via Overseerr (only for 4k/1080p)
Overseerr integration with support for per user permissions/quotas and issue submission
Ombi (V3/V4) integration with support for per user roles/quotas and issue submission
Fully configurable via a web portal

### 🏠 Project Homepage

https://github.com/thomst08/requestrr

### 💬 Your Discord username

layezee20

**Comment by funkypenguin** [comment]
Deployed and in the store :)
