### ISSUE TITLE
[app] Actual 

### ISSUE THREAD

**Issue by bsm-elf** [elfhosted/enhancements#39]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app
- [X] I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)

### 📜 Description

Actual is a local-first personal finance tool. It is 100% free and open-source, written in NodeJS, it has a synchronization element so that all your changes can move between devices without any heavy lifting.

### 🏠 Project Homepage

https://github.com/actualbudget/actual

### 💬 Your Discord username

bsm5702

**Comment by funkypenguin** [comment]
Rolled out and ready to rock!
