### ISSUE TITLE
[suggestion] Possibly allowing Tunarr access to other IPTV players beside Plex

### ISSUE THREAD

**Issue by ednagrinch** [elfhosted/enhancements#43]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app

### 🤕 What's not right?

Possibly allowing Tunarr access to other IPTV players beside Plex

### 🤯 Here's my idea!

Possibly allowing Tunarr access to other IPTV players beside Plex

### 🤔 On the other hand..

Possibly allowing Tunarr access to other IPTV players beside Plex

### 🤩 But will it fly?

Possibly allowing Tunarr access to other IPTV players beside Plex

### 💬 Your Discord username

ednagrinch

**Comment by funkypenguin** [comment]
This is deployed, but untested: https://store.elfhosted.com/product/tunarr-exposed/
